import {
  Rocket, Star, Heart, Zap, Book, Folder, File, Settings,
  Code, Terminal, Database, Cloud, Server, Globe, Mail,
  Calendar, Clock, Camera, Music, Video, Palette, Briefcase,
  GraduationCap, Trophy, Target, Flag, Home, Building, Car,
  Plane, Coffee, Pizza, Gift, ShoppingCart, CreditCard,
  DollarSign, TrendingUp, BarChart, PieChart, Lightbulb,
  Puzzle, Gamepad2, Dumbbell, Smile, Sun, Moon, Umbrella,
  Snowflake, Leaf, TreePine, Bug, Bird, Fish, Cat, Dog,
  Bookmark, Bell, Lock, Key, Shield, Wrench, MessageCircle,
  Share2, Users, Video as VideoCam,
  type LucideIcon,
} from "lucide-react";

export type IconEntry = {
  name: string;
  Icon: LucideIcon;
  keywords: string[];
};

export const ICON_LIBRARY: IconEntry[] = [
  { name: "Code", Icon: Code, keywords: ["github", "git", "code", "dev", "programming"] },
  { name: "MessageCircle", Icon: MessageCircle, keywords: ["twitter", "x", "social", "chat", "message"] },
  { name: "VideoCam", Icon: VideoCam, keywords: ["youtube", "video", "movie"] },
  { name: "Camera2", Icon: Camera, keywords: ["instagram", "photo", "camera"] },
  { name: "Users", Icon: Users, keywords: ["linkedin", "job", "career", "people", "team"] },
  { name: "Share2", Icon: Share2, keywords: ["facebook", "social", "share"] },
  { name: "Rocket", Icon: Rocket, keywords: ["rocket", "launch", "startup"] },
  { name: "Star", Icon: Star, keywords: ["star", "favorite"] },
  { name: "Heart", Icon: Heart, keywords: ["heart", "love", "like"] },
  { name: "Zap", Icon: Zap, keywords: ["zap", "fast", "energy", "lightning"] },
  { name: "Book", Icon: Book, keywords: ["book", "read", "study"] },
  { name: "Folder", Icon: Folder, keywords: ["folder", "files"] },
  { name: "File", Icon: File, keywords: ["file", "document"] },
  { name: "Settings", Icon: Settings, keywords: ["settings", "gear", "config"] },
  { name: "Code", Icon: Code, keywords: ["code", "dev", "programming"] },
  { name: "Terminal", Icon: Terminal, keywords: ["terminal", "console", "cli"] },
  { name: "Database", Icon: Database, keywords: ["database", "db", "data"] },
  { name: "Cloud", Icon: Cloud, keywords: ["cloud", "weather"] },
  { name: "Server", Icon: Server, keywords: ["server", "backend"] },
  { name: "Globe", Icon: Globe, keywords: ["globe", "world", "internet"] },
  { name: "Mail", Icon: Mail, keywords: ["mail", "email"] },
  { name: "Calendar", Icon: Calendar, keywords: ["calendar", "date", "schedule"] },
  { name: "Clock", Icon: Clock, keywords: ["clock", "time"] },
  { name: "Camera", Icon: Camera, keywords: ["camera", "photo"] },
  { name: "Music", Icon: Music, keywords: ["music", "song", "audio"] },
  { name: "Video", Icon: Video, keywords: ["video", "movie", "film"] },
  { name: "Palette", Icon: Palette, keywords: ["palette", "design", "art"] },
  { name: "Briefcase", Icon: Briefcase, keywords: ["briefcase", "work", "job"] },
  { name: "GraduationCap", Icon: GraduationCap, keywords: ["graduation", "school", "study"] },
  { name: "Trophy", Icon: Trophy, keywords: ["trophy", "award", "win"] },
  { name: "Target", Icon: Target, keywords: ["target", "goal"] },
  { name: "Flag", Icon: Flag, keywords: ["flag", "milestone"] },
  { name: "Home", Icon: Home, keywords: ["home", "house"] },
  { name: "Building", Icon: Building, keywords: ["building", "office"] },
  { name: "Car", Icon: Car, keywords: ["car", "vehicle"] },
  { name: "Plane", Icon: Plane, keywords: ["plane", "travel", "flight"] },
  { name: "Coffee", Icon: Coffee, keywords: ["coffee", "drink"] },
  { name: "Pizza", Icon: Pizza, keywords: ["pizza", "food"] },
  { name: "Gift", Icon: Gift, keywords: ["gift", "present"] },
  { name: "ShoppingCart", Icon: ShoppingCart, keywords: ["shopping", "cart", "buy"] },
  { name: "CreditCard", Icon: CreditCard, keywords: ["credit", "card", "payment"] },
  { name: "DollarSign", Icon: DollarSign, keywords: ["money", "dollar", "finance"] },
  { name: "TrendingUp", Icon: TrendingUp, keywords: ["trending", "growth", "chart"] },
  { name: "BarChart", Icon: BarChart, keywords: ["chart", "bar", "stats"] },
  { name: "PieChart", Icon: PieChart, keywords: ["chart", "pie", "stats"] },
  { name: "Lightbulb", Icon: Lightbulb, keywords: ["idea", "lightbulb", "tip"] },
  { name: "Puzzle", Icon: Puzzle, keywords: ["puzzle", "piece"] },
  { name: "Gamepad2", Icon: Gamepad2, keywords: ["game", "gaming", "controller"] },
  { name: "Dumbbell", Icon: Dumbbell, keywords: ["gym", "fitness", "workout"] },
  { name: "Smile", Icon: Smile, keywords: ["smile", "happy"] },
  { name: "Sun", Icon: Sun, keywords: ["sun", "weather", "day"] },
  { name: "Moon", Icon: Moon, keywords: ["moon", "night"] },
  { name: "Umbrella", Icon: Umbrella, keywords: ["umbrella", "rain"] },
  { name: "Snowflake", Icon: Snowflake, keywords: ["snow", "winter"] },
  { name: "Leaf", Icon: Leaf, keywords: ["leaf", "nature", "plant"] },
  { name: "TreePine", Icon: TreePine, keywords: ["tree", "nature"] },
  { name: "Bug", Icon: Bug, keywords: ["bug", "issue", "error"] },
  { name: "Bird", Icon: Bird, keywords: ["bird", "animal"] },
  { name: "Fish", Icon: Fish, keywords: ["fish", "animal"] },
  { name: "Cat", Icon: Cat, keywords: ["cat", "animal", "pet"] },
  { name: "Dog", Icon: Dog, keywords: ["dog", "animal", "pet"] },
  { name: "Bookmark", Icon: Bookmark, keywords: ["bookmark", "save"] },
  { name: "Bell", Icon: Bell, keywords: ["bell", "notification"] },
  { name: "Lock", Icon: Lock, keywords: ["lock", "security", "private"] },
  { name: "Key", Icon: Key, keywords: ["key", "password"] },
  { name: "Shield", Icon: Shield, keywords: ["shield", "security", "protect"] },
  { name: "Wrench", Icon: Wrench, keywords: ["wrench", "tool", "fix"] },
];

export const EMOJI_LIBRARY: { char: string; keywords: string[] }[] = [
  { char: "📄", keywords: ["document", "page", "file"] },
  { char: "📝", keywords: ["note", "write", "memo"] },
  { char: "📌", keywords: ["pin", "important"] },
  { char: "📎", keywords: ["clip", "attach"] },
  { char: "📁", keywords: ["folder"] },
  { char: "📂", keywords: ["folder", "open"] },
  { char: "🗂️", keywords: ["folder", "organize"] },
  { char: "📋", keywords: ["clipboard", "list"] },
  { char: "📅", keywords: ["calendar", "date"] },
  { char: "📊", keywords: ["chart", "graph", "stats"] },
  { char: "💡", keywords: ["idea", "tip", "lightbulb"] },
  { char: "🔥", keywords: ["fire", "hot", "trending"] },
  { char: "⭐", keywords: ["star", "favorite"] },
  { char: "✅", keywords: ["check", "done", "complete"] },
  { char: "🎯", keywords: ["target", "goal"] },
  { char: "🚀", keywords: ["rocket", "launch", "startup"] },
  { char: "🎨", keywords: ["art", "design", "paint"] },
  { char: "🎧", keywords: ["music", "headphones"] },
  { char: "🎬", keywords: ["movie", "video", "film"] },
  { char: "📚", keywords: ["books", "study", "read"] },
  { char: "🧠", keywords: ["brain", "idea", "think"] },
  { char: "💻", keywords: ["laptop", "code", "computer"] },
  { char: "🛠️", keywords: ["tools", "fix", "build"] },
  { char: "🔧", keywords: ["wrench", "fix"] },
  { char: "🔍", keywords: ["search", "find", "magnify"] },
  { char: "📈", keywords: ["chart", "growth", "up"] },
  { char: "📉", keywords: ["chart", "down"] },
  { char: "🗒️", keywords: ["note", "memo"] },
  { char: "🧩", keywords: ["puzzle", "piece"] },
  { char: "🎓", keywords: ["graduation", "school"] },
  { char: "🏠", keywords: ["home", "house"] },
  { char: "🌍", keywords: ["world", "globe", "earth"] },
  { char: "🌱", keywords: ["plant", "grow", "seed"] },
  { char: "☕", keywords: ["coffee", "drink"] },
  { char: "🍕", keywords: ["pizza", "food"] },
  { char: "🎮", keywords: ["game", "gaming"] },
  { char: "💰", keywords: ["money", "finance"] },
  { char: "⚙️", keywords: ["gear", "settings", "config"] },
  { char: "🔔", keywords: ["bell", "notification"] },
  { char: "❤️", keywords: ["heart", "love"] },
  { char: "😀", keywords: ["smile", "happy"] },
  { char: "😎", keywords: ["cool", "sunglasses"] },
  { char: "🥳", keywords: ["party", "celebrate"] },
  { char: "😴", keywords: ["sleep", "tired"] },
  { char: "🤔", keywords: ["think", "hmm"] },
  { char: "😢", keywords: ["sad", "cry"] },
  { char: "🎂", keywords: ["birthday", "cake"] },
  { char: "🎁", keywords: ["gift", "present"] },
  { char: "🏆", keywords: ["trophy", "win", "award"] },
  { char: "🏁", keywords: ["flag", "finish"] },
  { char: "🛒", keywords: ["cart", "shopping"] },
  { char: "💳", keywords: ["card", "payment"] },
  { char: "✈️", keywords: ["plane", "travel", "flight"] },
  { char: "🚗", keywords: ["car", "drive"] },
  { char: "🏢", keywords: ["office", "building"] },
  { char: "☀️", keywords: ["sun", "weather", "day"] },
  { char: "🌙", keywords: ["moon", "night"] },
  { char: "☔", keywords: ["rain", "umbrella"] },
  { char: "❄️", keywords: ["snow", "cold", "winter"] },
  { char: "🐛", keywords: ["bug", "insect", "error"] },
  { char: "🐦", keywords: ["bird", "twitter"] },
  { char: "🐟", keywords: ["fish"] },
  { char: "🐱", keywords: ["cat", "pet"] },
  { char: "🐶", keywords: ["dog", "pet"] },
  { char: "🔒", keywords: ["lock", "secure", "private"] },
  { char: "🔑", keywords: ["key", "password"] },
  { char: "🛡️", keywords: ["shield", "protect", "security"] },
];
